language: go

go: "1.10"

env:
  - GO_ENV=test DB_URL="mongodb://127.0.0.1:27017"

services:
  - mongodb
  - docker

go_import_path: github.com/I1820/lanserver

before_install:
  - PKGS=$(go list ./... ) # All the import paths

  # setup dependency management tool
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install linters
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/kisielk/errcheck

  # docker services
  - docker run -d -p 1883:1883 eclipse-mosquitto

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - dep ensure

script:
  - go vet -v $PKGS                   # go vet is the official Go static analyzer
  - errcheck -verbose $PKGS           # Check for unchecked errors
  - golint -set_exit_status $PKGS     # One last linter
  - buffalo test
